[package]
name = "pq-aggregation-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { path ="/Users/ardasaygan/Desktop/School_Materials/Cryptography/Rust/risc0/risc0/build", features=["unstable"]}

[package.metadata.risc0]
methods = ["guest"]
