[package]
name = "pq-aggregation-methods_2"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = {version = "1.2.6", features=["unstable"]}

[package.metadata.risc0]
methods = ["guest"]
